import fs from'node:fs';import{chromium}from'playwright';
const b=await chromium.launch({headless:true});
try{const p=await b.newPage({viewport:{width:1440,height:1000}}),s='#workGrid .work-card:not([hidden]) .tag-chip';
await p.goto(`https://kafka2306.github.io/anime/?year=2024&e2e=${process.env.GITHUB_RUN_ID}`,{waitUntil:'networkidle',timeout:120000});await p.waitForSelector(s,{timeout:60000});
const t=await p.locator(s).first().innerText();await p.locator(s).first().click();await p.waitForFunction(x=>new URL(location.href).searchParams.get('tag')===x,t);await p.waitForFunction(x=>document.querySelector('#yearTitle')?.textContent===`${x}の気になるランキング`,t);await p.waitForTimeout(400);
const r=await p.evaluate(t=>{const n=x=>String(x||'').normalize('NFKC').trim().toLocaleLowerCase('ja'),a=[...document.querySelectorAll('#workGrid .work-card:not([hidden])')].map(c=>{const m=c.querySelector('.work-card__meta')?.textContent||'';return{l:[...c.querySelectorAll('.tag-chip')].map(x=>x.textContent.trim()),c:+((m.match(/気になる\s*([\d,]+)件/)?.[1]||'').replaceAll(',','')),r:+(m.match(/タグ内 #(\d+)/)?.[1])}});let q=null,k=0;return{visible:a.length,exact:a.length>0&&a.every(x=>x.l.some(y=>n(y)===n(t))),descending:a.every((x,i)=>!i||a[i-1].c>=x.c),ranks:a.every((x,i)=>{if(x.c!==q)k=i+1;q=x.c;return x.r===k})}},t);
if(!r.exact||!r.descending||!r.ranks||!r.visible)throw Error(JSON.stringify(r));
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(250);const v=await p.evaluate(()=>{const d=x=>getComputedStyle(document.querySelector(x)).display,g=getComputedStyle(document.querySelector('#workGrid')).gridTemplateColumns.trim().split(/\s+/).length;return{mobile:d('.mobile-status'),filter:d('.responsive-control__summary'),columns:g,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1}});if(v.mobile!=='flex'||v.filter!=='flex'||v.columns!==1||v.overflow)throw Error(JSON.stringify(v));
fs.writeFileSync('browser-report.json',JSON.stringify({browser:'Chromium via Playwright',selected_tag:t,url_tag:new URL(p.url()).searchParams.get('tag'),ranking:r,viewport_390x844:v},null,2)+'\n');}finally{await b.close()}
